### PR TITLE
Fixes #15, build libcurl with winssl

### LINKED ISSUE #15: Failed to send the job. (SSL peer certificate or SSH remote key was not OK)
I have SSL runing on API URL, with Sectigo Limited cert installed. I was checking on google and is related to CURLOPT_SSL_VERIFYPEER or CURLOPT_SSL_VERIFYHOST. But is weird, because the SSL installed is valid.

### PR DESCRIPTION
**Pull request by Lihis**

### CODE REVIEW

**Comment by Lihis** [comment]
@donatocl can you verify this fixes the issue?

**Comment by donatocl** [comment]
@Lihis I will do the test now and let you know.

**Comment by donatocl** [comment]
I finished the build, but now an different error appears "Failed to send the job. (Unsupported Protocol)" and I saw the access log of the web side to see if the application is reaching the web side and the answer is not, so I assume with the "unsupported protocol" that the app is not able to communicate via https with web side.

**Comment by Lihis** [comment]
And the URL set in the settings starts with `https://`?

**Comment by donatocl** [comment]
Yes sir, with https

**Comment by donatocl** [comment]
Here is the info of the build process https://pastebin.com/h39rUB89 something at the end appears related to libcrypto.lib.

**Comment by Lihis** [comment]
Should not matter as it's only debug info what is missing.

I managed to reproduce with CI and the error indeed was `Unsupported protocol`. Seems that when we build cURL with winssl we don't get HTTPS protocol support but only HTTP:
```
-- Enabled protocols: DICT FILE FTP GOPHER HTTP IMAP POP3 RTSP SMTP TELNET TFTP
-- Enabled SSL backends: 
-- Configuring done
-- Generating done
```

**Comment by Lihis** [comment]
Maybe the WinSSL issue would need to be escalated to [Conan-Center Index](https://github.com/conan-io/conan-center-index) as for me it looks like an issue with it's build.

Reverted back to cURL with OpenSSL and added logic to load certificates.

**Comment by Lihis** [comment]
@donatocl when you have time could you test and verify it's working now?

**Comment by donatocl** [comment]
I can test in like 4 more hours and will let you know, thank you!

**Comment by donatocl** [comment]
@Lihis confirmed, this fixed the problem! Thank you sir!

**Pull request merged**
