### PR TITLE
Added 'isSpecial' to Job JSON, fixed clang-tidy warning

### PR DESCRIPTION
**Pull request by Lihis**
Added per further discussion in #31.

### CODE REVIEW

**Comment by donatocl** [comment]
Just to clarify, always will send isSpecial in JSON with a true or false, and when is true, source/destination company will dissapear?

**Comment by Lihis** [comment]
> Just to clarify, always will send isSpecial in JSON with a true or false, and when is true, source/destination company will dissapear?

Yes exactly like that.

**Comment by donatocl** [comment]
> 
> 
> > Just to clarify, always will send isSpecial in JSON with a true or false, and when is true, source/destination company will dissapear?
> 
> Yes exactly like that.

Thank you a lot! I will test in some hours and will use the v2 on the api version for sending the json post to /v2/... to avoid people (testers, like 13) that is using old app without this change, can't send the job info.

**Comment by Subtixx** [comment]
Works without any issues :)

**Comment by Lihis** [comment]
@Subtixx great. I'll check later that they for sure are missing but for now I'll merge this.

**Pull request merged**
