### PR TITLE
Fixes #21, option start on startup, allow to run in background

### LINKED ISSUE #21: Start on boot
Add option to enable start on boot.

### PR DESCRIPTION
**Pull request by Lihis**
@donatocl or @Subtixx could you test does this work on Windows?

### CODE REVIEW

**Comment by donatocl** [comment]
@Lihis sure, I will do it in some minutes!

**Comment by donatocl** [comment]
Test results: working fine, just a little problem with the "start on startup" I checked this, and works, I mean the program start in background when I logged in, but when I go again to settings appears as unchecked, so you need to check again and uncheck to disable the start on boot. If help, in the config.ini don't appear an "startonstartup=0" variable, just "runBackground=0", maybe that is why appears as unchecked.

**Comment by Lihis** [comment]
Thanks!

I didn't add it to the `config.ini` as users could disable it externally thus in the settings it would be seen as enabled but is actually disabled.

Pushed one commit, ready for a new round of testing.

**Comment by donatocl** [comment]
Fixed! Thank you @Lihis

**Comment by Lihis** [comment]
@donatocl thanks for testing!

**Pull request merged**
