### PR TITLE
Fixes #25, query server of it's capabilities

### LINKED ISSUE #25: Option to disable /truck endpoint
There should be a setting to disable sending to /truck endpoint. Because it can be quite the overhead the for API endpoint even when its not implemented

### PR DESCRIPTION
**Pull request by Lihis**

### CODE REVIEW

**Comment by donatocl** [comment]
And if the program is executed and the computer does not have internet, but after opening it, it connects to the Wi-Fi, for example, in this case, what option will it take by default? send or not send anything? Or will you continue trying to consult the webapi until you connect?

@Lihis is possible that you leave enable it by default?

**Comment by Lihis** [comment]
Good point, with this implementation the program will refuse to run until the user has internet connection which might not be preferable approach.

**Comment by Lihis** [comment]
Now it should allow to start the program when there is no internet connection. However status of the capabilities query is not displayed to the user..

@donatocl @Subtixx

**Comment by Subtixx** [comment]
Tested.

> 000.000.000.000 - - [04/Feb/2020:21:40:48 +0100] "POST /api/v1/capabilities HTTP/1.1" 200 1529 "-" "-"
> 000.000.000.000 - - [04/Feb/2020:21:41:06 +0100] "POST /api/v1/job HTTP/1.1" 200 832 "-" "-"

**Pull request merged**
