### PR TITLE
Build installer for Windows

### PR DESCRIPTION
**Pull request by Lihis**
Build installer for Windows in Appveyor so a it can be attached to releases.

Installer:
  - Installs the program per-user basis.
  - User can choose to enable "start on startup" during the installation.

Tested with Wine but should work with native Windows.

### CODE REVIEW

**Comment by donatocl** [comment]
Errors in VS2017 when compiling https://pastebin.com/bNG1TvP3
`
C:\Users\Donato\CMakeBuilds\39513d3b-5305-423c-9135-74fba073e7b1\build\x64-Release\gui\MainWindow.cpp.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl base::AboutDialog::~AboutDialog(void)" (??1AboutDialog@base@@UEAA@XZ) referenced in function "public: virtual __cdecl AboutDialog::~AboutDialog(void)" (??1AboutDialog@@UEAA@XZ) 

C:\Users\Donato\CMakeBuilds\39513d3b-5305-423c-9135-74fba073e7b1\build\x64-Release\gui\MainWindow.cpp.obj : error LNK2019: unresolved external symbol "public: __cdecl AboutDialog::AboutDialog(class wxWindow *)" (??0AboutDialog@@QEAA@PEAVwxWindow@@@Z) referenced in function "private: void __cdecl MainWindow::on_about(class wxCommandEvent &)" (?on_about@MainWindow@@AEAAXAEAVwxCommandEvent@@@Z) 

C:\Users\Donato\CMakeBuilds\39513d3b-5305-423c-9135-74fba073e7b1\build\x64-Release\bin\ets2-job-logger.exe : fatal error LNK1120: 2 unresolved externals 
`

**Comment by Lihis** [comment]
Can not be related to this PR, does that happen in `master` branch?

**Comment by donatocl** [comment]
Just happen in this PR.

**Comment by Lihis** [comment]
Visual Studio is borked? It's building just fine in Appveyor.

**Comment by donatocl** [comment]
My bad, sorry, I was using the old cmake cache generated by VS2017, I deleted the cache and regenerate again and now is compiled wihtout errors :), thank you!

I will test the installer and answer again in some minutes to confirm that is working.

**Comment by donatocl** [comment]
All is working great!

**Comment by donatocl** [comment]
Maybe will be a good idea to have an update procedure like this https://stackoverflow.com/a/53079610 avoiding the /silent part because the idea is that it does not generate problems, out there someone has the game open and an update closes the program to unlock the plugin file and install the update and with the game open that cannot be done. But will be helpful that the app check like every 30 minutes the API URL with /version endpoint and /version will return actual_version and download_url so the APP can compare the version that is configured in some variable in the app code against actual_version and if actual_version > version then user download_url to download and run the new installer.

**Comment by Lihis** [comment]
That would be nice.

If `Advanced Installer` has that as a feature I wouldn't mind if someone sponsor a license so it can be used in `Appveyor`.

**Pull request merged**
